# config for cifar10
input_size: 32 # 112 in the paper
channel: 3

# train
random_seed: 0
epochs: 0
steps: 300000
save_step: 10000
beta_1: 0.5
batch_size: 64
latent_dim: 256 # 1024 in the paper
gen:
  learning_rate: 0.0002
  n_layer: 7
  n_filter: 256
dis:
  learning_rate: 0.0002
  n_layer: 4
  n_filter: 64

# test
test_step: 100
test_batch_size: 64

# directory
checkpoint_dir: ./checkpoints

# data
dataset:
  data_dir: ../dataset/cifar10
  train_data_txt:
  train_test_split: true
  labeled_dir: true
  cache: true
