# config for mnsit
input_size: 28
channel: 1

# train
random_seed: 0
epochs: 100
learning_rate: 0.0002
batch_size: 128
latent_dim: 32

# test
test_batch_size: 36

# directory
train_data_txt: ../dataset/mnist/train.txt
output_dir: ./output
checkpoint_dir: ./checkpoint
log_dir: ./log
