# config for mnsit
input_size: 28
channel: 1

# train
random_seed: 0
epochs: 100
learning_rate: 0.0002
batch_size: 64
latent_dim: 32

# test
test_batch_size: 64

# directory
checkpoint_dir: ./checkpoint

# data
dataset:
  data_dir: ../dataset/mnist
  train_data_txt:
  train_test_split: true
  labeled_dir: true
