# config for cifar10
input_size: 32
channel: 3

# train
random_seed: 0
epochs: 100
learning_rate: 0.0002
beta_1: 0.5
batch_size: 64
latent_dim: 128
gen:
  n_layer: 4
  n_filter: 512 # 512, 256, 128, 64
dis:
  n_layer: 4
  n_filter: 64 # 64, 128, 256, 512

# test
test_batch_size: 64

# directory
checkpoint_dir: ./checkpoints

# data
dataset:
  data_dir: ../dataset/cifar10
  train_data_txt:
  train_test_split: true
  labeled_dir: true
