# config for cifar10
input_size: 32
channel: 3

# train
random_seed: 0
epochs: 1000
learning_rate: 0.0002
beta_1: 0.5
batch_size: 64
latent_dim: 128
gen:
  n_layer: 3
  n_filter: 256 # 256, 128, 64
dis:
  n_layer: 3
  n_filter: 64 # 64, 128, 256

# test
test_batch_size: 64

# directory
checkpoint_dir: ./checkpoint

# data
dataset:
  data_dir: ../dataset/cifar10
  train_data_txt:
  train_test_split: true
  labeled_dir: true
