# config for mnsit
input_size: 32
channel: 1

# train
random_seed: 0
epochs: 10000
learning_rate: 0.0002
beta_1: 0.5
batch_size: 128
latent_dim: 32
gen:
  n_layer: 3
  n_filter: 64
dis:
  n_layer: 4
  n_filter: 32

# directory
train_data_txt: ../dataset/mnist/train.txt
checkpoint_dir: ./checkpoint/DCGAN
log_dir: ./log
