# config for mnist
input_size: 32
channel: 1

# train
random_seed: 0
epochs: 100
steps: 0
save_step: 10000
learning_rate: 0.0002
beta_1: 0.5
batch_size: 64
latent_dim: 32
gen:
  n_layer: 2
  n_filter: 128 # 128, 64
dis:
  n_layer: 2
  n_filter: 32 # 32, 64

# test
test_step: 100
test_batch_size: 64

# directory
checkpoint_dir: ./checkpoints

# data
dataset:
  data_dir: ../datasets/mnist
  train_data_txt:
  train_test_split: true
  labeled_dir: true
  cache: true
