# config for MS COCO 2014, wikiart
input_size: 256
channel: 3

encoder:
  pretrained_model: vgg19
  output_layers:
    - block1_conv1
    - block2_conv1
    - block3_conv1
    - block4_conv1

decoder:
  n_filter: 256

# train
steps: 160000
save_step: 10000
batch_size: 4
learning_rate: 0.0001
beta_1: 0.5

# test
test_step: 100
test_batch_size: 9

# directory
checkpoint_dir: ./checkpoints
style_image:

# data
dataset:
  content:
    data_dir: ../dataset/coco14
    train_data_txt:
    train_test_split: false
    labeled_dir: false
    cache: false
  style:
    data_dir: ../dataset/wikiart
    train_data_txt:
    train_test_split: false
    labeled_dir: false
    cache: false
