# config for MS COCO 2014
input_size: 256
channel: 3

feature_extrator:
  pretrained_model: vgg19
  content_layers:
    - block4_conv2
  style_layers:
    - block1_conv1
    - block2_conv1
    - block3_conv1
    - block4_conv1
    - block5_conv1
transform_net:
  n_residual: 5
  n_filter: 32

# train
epochs: 0
steps: 40000
save_step: 10000
batch_size: 4
learning_rate: 0.001
beta_1: 0.5
content_weight: 0.1
total_variation_weight: 10000

# test
test_step: 100
test_batch_size: 9

# directory
checkpoint_dir: ./checkpoints
style_image:

# data
dataset:
  data_dir: ../dataset/coco14
  train_data_txt:
  train_test_split: false
  labeled_dir: false
  cache: false
